services:
  - type: web
    name: churnaizer-api
    env: python
    pythonVersion: 3.11.0
    buildCommand: pip install -r churnaizer/requirements.txt
    startCommand: uvicorn churnaizer.app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/predict
    autoDeploy: true