services:
  - type: web
    name: churnaizer-api
    env: python
    buildCommand: pip install -r churnaizer/requirements.txt
    startCommand: gunicorn main:app --chdir churnaizer --bind 0.0.0.0:$PORT
    healthCheckPath: /predict
    autoDeploy: true